with open('cuisinemap_update.html', 'r', encoding='utf-8', errors='replace') as f:
    content = f.read()

# These recipes will be injected with exact key matching
new_recipes = """
"Canard \u00e0 l'orange GF \u2014 duck in orange sauce with rice":{img:"",ings:["2 duck breasts","juice of 3 oranges","zest of 1 orange","2 tbsp honey","1 cup chicken stock","thyme","salt and pepper","steamed rice"],steps:["Score duck skin and season generously.","Render skin side down 12 minutes until very crispy.","Flip and cook 5 minutes then rest 10 minutes.","Make orange sauce by reducing juice, zest, honey and stock until glossy.","Slice duck and serve over steamed rice with sauce."]},
"Canard \u00e0 l'orange \u2014 duck in orange sauce dairy-free":{img:"",ings:["2 duck breasts","juice of 3 oranges","zest of 1 orange","2 tbsp honey","1 cup chicken stock","thyme","salt and pepper"],steps:["Score duck skin and season with salt.","Render skin side down 12 minutes until crispy.","Flip and cook 5 minutes then rest.","Make orange sauce with juice, zest, honey and stock.","Slice and serve with sauce, naturally dairy free."]},
"Canard \u00e0 l'orange \u2014 duck in orange sauce no side":{img:"",ings:["2 duck breasts","juice of 3 oranges","zest of 1 orange","2 tbsp honey","1 cup stock","garlic","thyme","salt and pepper"],steps:["Score duck skin and season.","Render skin side down 12 minutes until crispy.","Flip and cook 5 minutes, rest 10 minutes.","Make orange sauce by reducing juice, zest, honey and stock.","Slice duck and serve with sauce only, no side."]},
"Canard \u00e0 l'orange \u2014 roast duck breast in orange sauce":{img:"",ings:["2 large duck breasts","juice of 3 oranges","zest of 1 orange","2 tbsp honey","1 cup rich chicken stock","garlic","fresh thyme","salt and pepper"],steps:["Score duck skin deeply and season generously with salt.","Place skin side down in cold pan over medium heat.","Render 12 minutes until deeply golden and crispy.","Flip, cook 5 minutes for medium rare, rest 10 minutes.","Reduce orange juice, zest, honey and stock to glossy sauce, pour over sliced duck."]},
"Gigot d'agneau avec flageolets GF \u2014 leg of lamb GF":{img:"",ings:["1 whole leg of lamb","8 cloves garlic","fresh rosemary","4 tbsp olive oil","juice of 1 lemon","400g tinned flageolet beans","fresh thyme","salt and pepper"],steps:["Stud lamb with garlic and rosemary, rub with olive oil and lemon.","Season generously with salt and pepper.","Roast at 200C for 20 minutes then 180C for 1 hour.","Rest 15 minutes before carving.","Serve with warm flageolet beans seasoned with thyme and olive oil."]},
"Gigot d'agneau avec haricots verts \u2014 lamb with green beans":{img:"",ings:["1 whole leg of lamb","6 cloves garlic","fresh rosemary","olive oil","salt and pepper","400g fresh green beans","2 tbsp butter","juice of half lemon"],steps:["Stud lamb with garlic and rosemary, rub with olive oil and season.","Roast at 200C for 20 minutes then 180C for 1 hour, rest 15 minutes.","Boil green beans in salted water 5 minutes until just tender.","Drain and toss with butter and lemon juice.","Carve lamb and serve with buttered green beans."]},
"Gigot d'agneau \u2014 slow-roasted lamb dairy-free":{img:"",ings:["1 whole leg of lamb","8 cloves garlic","fresh rosemary and thyme","4 tbsp olive oil","1 cup dry white wine","salt and pepper"],steps:["Stud lamb with garlic and herbs, rub with olive oil and season.","Pour wine into roasting tin.","Roast at 160C for 3 hours until very tender.","Rest 15 minutes.","Serve with pan juices, completely dairy free."]},
"Gigot d'agneau \u2014 slow-roasted leg of lamb with flageolet beans":{img:"",ings:["1 whole leg of lamb","8 cloves garlic","fresh rosemary","4 tbsp olive oil","1 cup white wine","400g tinned flageolet beans","fresh thyme","salt and pepper"],steps:["Stud lamb with garlic and rosemary, rub with olive oil and season.","Pour wine around lamb in roasting tin.","Roast at 200C for 20 minutes then 160C for 2 hours.","Rest 20 minutes before carving.","Warm flageolet beans with thyme and serve alongside carved lamb."]},
"Jus d'orange avec tartine \u2014 orange juice with toast":{img:"",ings:["4 fresh oranges","4 slices bread","2 tbsp butter","2 tbsp jam or honey"],steps:["Halve and juice oranges, pour into glasses.","Toast bread until golden.","Spread with butter while hot.","Add jam or honey.","Serve alongside fresh orange juice."]},
"Porridge \u00e0 l'avoine avec fruits \u2014 oat porridge with fruit":{img:"",ings:["1 cup rolled oats","2 cups milk","1 tbsp honey","pinch of salt","assorted fresh fruit","pinch of cinnamon"],steps:["Bring milk to gentle simmer.","Add oats and pinch of salt.","Cook 5 minutes stirring until creamy.","Stir in honey.","Serve topped with fresh fruit and cinnamon."]},
"Soupe \u00e0 l'ail \u2014 garlic and bread soup vegan":{img:"",ings:["2 whole heads garlic","4 thick slices stale bread","1 litre vegetable stock","4 tbsp olive oil","fresh flat leaf parsley","salt and pepper"],steps:["Peel garlic cloves and simmer in stock 20 minutes until very soft.","Lightly toast stale bread and place in bowls.","Blend garlic and stock until smooth.","Season with salt and pepper.","Pour over bread, drizzle olive oil and scatter parsley."]},
"Soupe \u00e0 l'oignon GF sans cro\u00fbton \u2014 onion soup no crouton":{img:"",ings:["6 large onions sliced","1 litre beef or vegetable stock","1 cup white wine","3 tbsp butter","thyme","bay leaf","salt and pepper","Gruyere to serve"],steps:["Caramelise onions in butter over low heat 45 minutes until golden.","Add wine and reduce.","Add stock, thyme and bay leaf, simmer 20 minutes.","Season well.","Serve without crouton, offer Gruyere separately for GF version."]},
"Soupe \u00e0 l'oignon gratin\u00e9e \u2014 French onion soup with Gruy\u00e8re crouton":{img:"",ings:["6 large onions sliced","1 litre beef stock","1 cup dry white wine","3 tbsp butter","thyme","bay leaf","salt and pepper","4 baguette slices","150g Gruyere grated"],steps:["Caramelise onions in butter over very low heat 45 minutes.","Add wine and reduce by half.","Add stock, thyme and bay leaf, simmer 20 minutes, season.","Ladle into oven-safe bowls and float baguette on top.","Pile Gruyere over and grill until bubbling and golden."]},
"Soupe \u00e0 l'oignon sans cro\u00fbton \u2014 onion soup no crouton":{img:"",ings:["6 large onions sliced","1 litre stock","1 cup white wine","3 tbsp butter","thyme","bay leaf","salt and pepper"],steps:["Caramelise onions in butter 45 minutes.","Add wine and reduce.","Add stock and herbs, simmer 20 minutes.","Season generously.","Serve without crouton."]},
"Soupe \u00e0 l'oignon sans fromage \u2014 onion soup dairy-free":{img:"",ings:["6 large onions sliced","1 litre vegetable stock","1 cup white wine","3 tbsp olive oil","thyme","bay leaf","salt and pepper","baguette slices"],steps:["Caramelise onions in olive oil 45 minutes.","Add wine and reduce.","Add stock and herbs, simmer 20 minutes.","Season generously.","Serve with baguette, no cheese for dairy-free version."]},
"Soupe \u00e0 l'oignon \u2014 French onion soup with Gruy\u00e8re":{img:"",ings:["6 large onions sliced","1 litre rich beef stock","1 cup dry white wine","3 tbsp butter","thyme","bay leaf","salt and pepper","thick baguette slices","150g Gruyere grated"],steps:["Caramelise onions in butter over very low heat 45 minutes until deeply golden.","Add wine and cook until reduced.","Add stock, thyme and bay leaf, simmer 20 minutes.","Season very generously.","Ladle into bowls, top with baguette and Gruyere, grill until bubbling."]},
"Buddha's delight":{img:"",ings:["100g tofu fried","50g lily buds soaked","50g wood ear mushrooms soaked","50g glass noodles soaked","100g baby bok choy","2 carrots sliced","50g bamboo shoots","3 tbsp soy sauce","1 tbsp sesame oil","2 cloves garlic","oil"],steps:["Soak lily buds, mushrooms and glass noodles separately until soft.","Fry garlic in oil until fragrant.","Add carrots and bamboo shoots, stir fry 3 minutes.","Add tofu, mushrooms, lily buds, bok choy and noodles.","Season with soy sauce and sesame oil, toss gently and serve."]},
"Buddha's delight \u2014 jai":{img:"",ings:["mixed dried and fresh vegetables","glass noodles","tofu","lily buds","wood ear mushrooms","bamboo shoots","soy sauce","sesame oil","garlic","oil"],steps:["Soak all dried ingredients until soft.","Fry garlic in oil.","Add harder vegetables first and cook.","Add softer vegetables, tofu and noodles.","Season with soy sauce and sesame oil."]},
"Fett'unta con cannellini":{img:"",ings:["4 thick slices Tuscan bread","400g tinned cannellini beans","3 cloves garlic","4 tbsp extra virgin olive oil","fresh rosemary","salt and pepper","lemon juice"],steps:["Grill bread over open flame or under grill until charred on both sides.","While hot, rub cut garlic clove firmly over each slice.","Drizzle very generously with best olive oil.","Warm cannellini beans with rosemary, garlic and olive oil.","Top grilled bread with beans, season and squeeze lemon over."]},
"Fett'unta with cannellini":{img:"",ings:["4 thick slices Tuscan bread","400g tinned cannellini beans","3 cloves garlic","4 tbsp extra virgin olive oil","fresh rosemary","salt and pepper"],steps:["Grill bread until nicely charred on both sides.","Rub hot bread with cut garlic clove while still hot.","Drizzle generously with extra virgin olive oil.","Warm beans with rosemary and olive oil.","Spoon beans over bread and season with salt and pepper."]},
"Fett'unta with white beans and sage":{img:"",ings:["4 thick slices country bread","400g tinned white beans","3 cloves garlic","fresh sage leaves","4 tbsp extra virgin olive oil","salt and pepper","lemon"],steps:["Grill bread until charred and crispy on both sides.","Rub with garlic while hot.","Fry sage leaves in olive oil until crispy.","Warm beans in same oil with garlic, season well.","Top bread with beans, add crispy sage and squeeze lemon."]},
"Penne all'arrabbiata":{img:"",ings:["400g penne","400g tinned crushed tomatoes","4 cloves garlic sliced","2 tsp chilli flakes","4 tbsp olive oil","large bunch fresh flat leaf parsley","salt","pecorino to serve"],steps:["Fry garlic and chilli flakes in olive oil over medium heat until golden.","Add tinned tomatoes and season with salt.","Simmer 15 minutes until sauce thickens.","Cook penne in well salted boiling water until al dente.","Drain and toss with spicy sauce, scatter fresh parsley and serve with pecorino."]},
"Po'boy sandwich":{img:"",ings:["2 French baguettes or hoagie rolls","300g fried shrimp or oysters or roast beef","shredded lettuce","sliced tomatoes","pickles","remoulade sauce","hot sauce"],steps:["Split rolls lengthways without cutting all the way through.","Make remoulade with mayo, mustard, horseradish and hot sauce.","Spread remoulade generously inside roll.","Fill with chosen protein, fried shrimp or oysters are classic.","Top with shredded lettuce, tomato and pickles, add hot sauce."]},
"Eggs with tomato and za'atar":{img:"",ings:["4 eggs","3 ripe tomatoes sliced","2 tbsp za'atar spice blend","3 tbsp olive oil","salt and pepper","warm flatbread"],steps:["Slice tomatoes and arrange on plate.","Drizzle with olive oil and sprinkle za'atar generously.","Fry or poach eggs to your preference.","Place eggs alongside or on top of tomatoes.","Season with salt and pepper and serve with warm flatbread."]},
"Hummus with za'atar and olive oil":{img:"",ings:["400g tinned chickpeas","4 tbsp tahini","juice of 2 lemons","3 cloves garlic","4 tbsp olive oil","2 tbsp za'atar","salt","warm flatbread"],steps:["Blend chickpeas with tahini, lemon and garlic until very smooth.","Season with salt and adjust lemon to taste.","Spread in shallow bowl making swirl with back of spoon.","Drizzle generously with olive oil.","Sprinkle za'atar over and serve with warm flatbread."]},
"Labneh with GF crackers":{img:"",ings:["300g labneh strained yogurt cheese","3 tbsp olive oil","dried mint","za'atar","gluten free crackers","cucumber slices","olives"],steps:["Place labneh in serving bowl.","Drizzle with olive oil.","Sprinkle dried mint and za'atar over.","Arrange gluten free crackers around.","Serve with cucumber slices and olives."]},
"Labneh with cucumber":{img:"",ings:["300g labneh","1 large cucumber diced or sliced","3 tbsp olive oil","dried mint","za'atar","salt","warm flatbread"],steps:["Spread labneh on plate or in bowl.","Drizzle with olive oil.","Sprinkle dried mint over.","Arrange cucumber alongside or on top.","Season with salt and serve with flatbread."]},
"Labneh with cucumbers":{img:"",ings:["300g labneh","2 cucumbers sliced","3 tbsp olive oil","dried mint","za'atar","olives","flatbread"],steps:["Place labneh in serving bowl.","Drizzle olive oil generously over.","Sprinkle za'atar and dried mint.","Arrange sliced cucumbers and olives alongside.","Serve with warm flatbread."]},
"Labneh with za'atar":{img:"",ings:["300g labneh","3 tbsp olive oil","2 tbsp za'atar","olives","flatbread"],steps:["Spread labneh on plate.","Drizzle with olive oil.","Sprinkle za'atar generously.","Add olives alongside.","Serve with warm flatbread."]},
"Labneh with za'atar and olive oil":{img:"",ings:["300g labneh","4 tbsp extra virgin olive oil","2 tbsp za'atar spice blend","olives","warm flatbread or pita"],steps:["Place labneh in shallow bowl.","Drizzle very generously with best olive oil.","Sprinkle za'atar all over.","Scatter olives around.","Serve with warm flatbread or pita for dipping."]},
"Scrambled eggs with za'atar":{img:"",ings:["4 eggs","2 tbsp butter","1 tbsp za'atar","salt and pepper","warm flatbread","olive oil"],steps:["Whisk eggs with salt and pepper.","Melt butter in pan over low heat.","Scramble eggs slowly until just creamy.","Transfer to plate and sprinkle za'atar generously.","Drizzle with olive oil and serve with warm flatbread."]},
"Sliced tomato with za'atar":{img:"",ings:["4 large ripe tomatoes","2 tbsp za'atar","3 tbsp extra virgin olive oil","sea salt flakes","fresh flatbread"],steps:["Slice tomatoes thickly.","Arrange on plate.","Drizzle generously with olive oil.","Sprinkle za'atar over all slices.","Season with sea salt flakes and serve with flatbread."]},
"""

# Insert before the closing of STATIC_RECIPES
# Find a good insertion point - just before the last closing brace of STATIC_RECIPES
marker = '// ── FRENCH MISSING ──'
if marker in content:
    insert_pos = content.find(marker)
    content = content[:insert_pos] + new_recipes + '\n' + content[insert_pos:]
    print("Inserted before French Missing section")
else:
    # Try to insert before Mediterranean section
    marker2 = '// ── MEDITERRANEAN ──'
    if marker2 in content:
        insert_pos = content.find(marker2)
        content = content[:insert_pos] + new_recipes + '\n' + content[insert_pos:]
        print("Inserted before Mediterranean section")
    else:
        print("Could not find insertion point!")

with open('cuisinemap_update.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done!")
